### ISSUE TITLE
Allow users to specify offset / timestamp to configure starting point for Event Hub

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-eventhubs-extension#64]
Users today cannot control when their Event Hub starts to run from - it generally starts from the very beginning which can mean lots of data which adds latency/wasted compute/etc. Users should be able to specify how far back the Event Hubs trigger starts.

From: https://feedback.azure.com/forums/355860/suggestions/19085314

**Comment by fabiocav** [comment]
Assuming this is work in progress and moving to sprint 79. Please let me know if you need to decompose this issue for sprint assignment. Thanks!

**Comment by ishepherd** [comment]
Hope we can get soon!

We do need the capability from @paulbatum's example, that it can decide this in code. The code can, e.g., read it from app settings.

Just checking you're not going to make it fixed in the host.json or anything like that 😄

**Comment by sidkri** [comment]
@ishepherd, this is in development, I haven't had a chance to roll it out yet, sorry.  The plan for the initial version is to support configuring the initial offset to be the end of the stream on first run of by a consumer group.  I'll have a PR out and feedback is welcome.

**Comment by fabiocav** [comment]
@sidkri should this be moved to sprint 82? Are you targeting a different sprint?

**Comment by sidkri** [comment]
Moved to 82.  I have been side tracked by other issues.  Will get this out in 82.

**Comment by fabiocav** [comment]
Just following up on this. Should we move to 83?

**Comment by sidkri** [comment]
Done.

**Comment by drdamour** [comment]
what'd really be slick is if the extension could inject a management client that let me muck with the offsets in a safe way even pausing/restarting the EventProcessHost for me

**Comment by fabiocav** [comment]
PR currently in draft. Moving to sprint 88

**Comment by sidkri** [comment]
FYI, I have a PR out to support configurable initial offset of "FromStart", "FromEnd" and "FromEnqueuedTime".  Please review the PR description for more details and feel free to @ and send me any questions here or on the PR.

**Comment by sidkri** [comment]
PR merge closed the issue but package is not released yet.  I'll update here when the package has been published.  Working on updating documentation to explain the new configuration settings now.

**Comment by fabiocav** [comment]
@sidkri is this still waiting on a package release? I can work with you on that if needed.

**Comment by sidkri** [comment]
@fabiocav we have a flakey test from before the change that is making the pipeline fail intermittently so trying to track that down before rolling this out.

**Comment by sidkri** [comment]
This feature has been published as version 4.2.0: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs

I have a PR out to update the Azure docs explaining how the new configuration works, until that is published, please refer to the details on the PR to configure your app using 4.2.0 to start from the end of the stream of a specific enqueued time.  Note: Specify the timezone if using enqueued time or it will assume the date and time are in UTC.
PR: https://github.com/Azure/azure-functions-eventhubs-extension/pull/79

**Comment by benchoi93** [comment]
Hi. Thank you for the new feature, but I have a problem.

When I stop a function with "fromEnd" setting and then restart it a few moments later, the function does not read the latest events, but the function reads the events from the stopped time. If I erase the blob in the "azure-webjobs-eventhub," and then restart, obviously it starts reading the latest events.

I think when we restart the function with "fromEnd" setting, there should be some method to overwrite the blob so that the function reads the latest events in the eventhub. In the meantime, I think I can manually erase the blob everytime I stop and restart the function.

**Comment by sidkri** [comment]
@benchoi93 you have to remove the checkpoint blobs from storage - this is by design.  The configuration setting is only for "first run" of a Function app.  Deleting checkpoint blobs is not supported.  Function Apps can run across multiple machines and a restart does not happen on all machines at the same time - deleting of checkpoint blobs by one machine would result in other machines creating a new checkpoint and result in gaps in processing.

**Comment by paulbatum** [comment]
The docs for the new initialOffsetOptions setting are here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=csharp#functions-2x-and-higher

**Comment by drwhitey1** [comment]
Is this live in any regions? I don't see the settings in eventhuboptions output in appinsights (its definately set): 

EventHubOptions { "BatchCheckpointFrequency": 5, "EventProcessorOptions": { "EnableReceiverRuntimeMetric": false, "InvokeProcessorAfterReceiveTimeout": false, "MaxBatchSize": 64, "PrefetchCount": 128, "ReceiveTimeout": "00:01:00" }, "PartitionManagerOptions": { "LeaseDuration": "00:00:30", "RenewInterval": "00:00:10" } }

If not, any ETA?

**Comment by sidkri** [comment]
@drwhitey1 please ensure you are referencing the 4.2.0+ of the Microsoft.Azure.WebJobs.Extensions.EventHubs.  This is available in 2.x of the extensions bundle or you can reference it directly as well.  More information in our docs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles

Check that your host.json has:
"extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[2.*, 3.0.0)"
    }

**Comment by chongzhang** [comment]
The extension bundle release 2.4.0 is still using eventHub 4.1.1, https://github.com/Azure/azure-functions-extension-bundles/blob/2.4.0/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json#L25. Is there going to be a new bundle release to use eventHub 4.2.0?

**Comment by maniraj1234** [comment]
Is there a way to set InitialOffsetPointer to UTCTimeNow - 30min.
and on service restart, it should be able to pick Min(checkpoint, initialoffsetpointer)?

**Comment by paulbatum** [comment]
@maniraj1234 No. The initialOffset setting simply configures how the system behaves in the absence of a checkpoint. If there is a checkpoint present, it always uses that. So even if you used some of the tricks I described above to dynamically set the initialoffset to UTCTimeNow - 30min, the min logic you outlined would not be present. The checkpoint would be used, or the initial offset would be used.

**Comment by maniraj1234** [comment]
Any thoughts on what can be done to achieve the best of both? Min(checkpoint, UTCTimeNow-30mins) ?

**Comment by paulbatum** [comment]
Not sure what you mean by best of both. I am also not sure why you'd want to do min(checkpoint,now-30m) because that means every time the application restarts or scales out to a new instance, if its checkpoints were up to date then the now-30m would be smaller and that means the last 30 minutes of data would be reprocessed. I am also not sure how you would achieve this.

**Comment by maniraj1234** [comment]
Sorry, I meant the otherway around. If checkpoint is within last 30 mins, it should pick checkpoint otherwise utctimeNow - 30mins. So that it won't process data older than 30 mins.

**Comment by paulbatum** [comment]
I see, so you want the same thing as InitialOffset:fromEnd but -30 minutes. To do that you'd need to use code to calculate now()-30min and then explicitly set it. My comment above shows how to use code to configure the initialOffset:
https://github.com/Azure/azure-functions-eventhubs-extension/issues/64#issuecomment-555277623

**Comment by maniraj1234** [comment]
@paulbatum that can only change initial offset but in my case we have a checkpoint, we need to compare checkpoint and now-30 minutes. is it possible to do so?

**Comment by paulbatum** [comment]
Sorry I misread your comment. I don't know how to do what you want, short of writing a separate program that interacts with eventhub and storage to manually set the checkpoints.

**Comment by brijgithub** [comment]
in the event processor option use EventPosition.FromEnd() so that it will pick up latest event but before that please dont forget to delete the offset data stored in azure-webjobs-eventhub in the storage account you connected to your function app otherwise it will override the event processor option settings ,if you are debugging locally use storage explorer for deleting
