### ISSUE TITLE
Retry loop should cancel on lease lost

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-eventhubs-extension#92]
When using a [retry policy](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp) with an eventhub trigger, the retry loop should be cancelled if the lease is lost. If the retry loop is not cancelled, this will lead to duplicate message processing or potentially broken message ordering, where one machine is waiting to retry a message while another machine has already acquired the lease and started processing. 

@alrod notes:

> It looks like we do not pass the cancellation token properly from “EventHubListener” to “EventProcessor”, we just create it [here](https://github.com/Azure/azure-functions-eventhubs-extension/blob/5eb8543e47b448eb3b485a571a2ceb1ab404650f/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Listeners/EventHubListener.cs#L116).

**Comment by mathewc** [comment]
Seems like the underlying issue here is that the retry logic [here](https://github.com/Azure/azure-webjobs-sdk/blob/3f4ec78be9f43bb041937425ced00b341883aa42/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutorExtensions.cs#L20) doesn't fully respect the CancellationToken passed in.  In the loop it should check for cancellation before beginning a new attempt, and it should also pass the token in on the Task.Delay. If all of this is done, when the caller requests cancellation (e.g. due to a lost lease) retries will stop.

**Comment by alrod** [comment]
Fixed in track2:
https://github.com/Azure/azure-sdk-for-net/pull/27340
